import type { Ref } from 'react'
import { ArrowRight, ChevronDown, CircleAlert, Fuel, Share2 } from 'lucide-react'
import { distanceFromKm, formatCurrency, unitLabels, volumeFromLitres, type TripDraft, type TripResult, type UnitSystem } from '../../domain'
import { classes } from '../styles'

type ShareStatus = 'idle' | 'sharing' | 'shared' | 'downloaded' | 'error'
type Props = { draft: TripDraft; result: TripResult | null; unitSystem: UnitSystem; stopsById: Map<string, string>; panelRef: Ref<HTMLElement>; shareStatus: ShareStatus; shareError: string; shareMessageCopied: boolean; onReveal: () => void; onShare: () => void }

export function ResultsPanel({ draft, result, unitSystem, stopsById, panelRef, shareStatus, shareError, shareMessageCopied, onReveal, onShare }: Props) {
  const units = unitLabels(unitSystem)
  const calculationLegs = result ? draft.legs.map((leg) => { const riders = draft.people.filter((person) => person.assignedLegIds.includes(leg.id)); const cost = (leg.distanceKm ?? 0) / draft.fuelSettings.fuelEconomyKmpl! * draft.fuelSettings.fuelPricePerLitre!; return { leg, riders, cost } }) : []
  return <section ref={panelRef} id="results" className={classes('results-card')} aria-labelledby="results-title" aria-live="polite">
    <div className={classes('results-heading')}><div><span className={classes('results-kicker')}>Your split</span><h2 id="results-title">Journey summary</h2></div><Fuel /></div>
    {!result ? <div className={classes('results-empty')}><p>Complete the trip details to see your fair split. Once they are valid, the split updates automatically.</p><button className={classes('primary-button')} type="button" onClick={onReveal}>Check trip details <ArrowRight size={18} /></button></div> : <>
      <div className={classes('totals')}><div><span>Total distance</span><strong>{distanceFromKm(result.totalDistanceKm, unitSystem).toLocaleString(undefined, { maximumFractionDigits: 2 })} {units.distance}</strong></div><div><span>Fuel used</span><strong>{volumeFromLitres(result.totalLitres, unitSystem).toLocaleString(undefined, { maximumFractionDigits: 2 })} {units.volume}</strong></div>{result.totalAdditionalCost > 0 && <><div><span>Fuel cost</span><strong>{formatCurrency(result.totalFuelCost, draft.fuelSettings.currency)}</strong></div><div><span>Additional expenses</span><strong>{formatCurrency(result.totalAdditionalCost, draft.fuelSettings.currency)}</strong></div></>}<div className={classes('total-cost')}><span>{result.totalAdditionalCost > 0 ? 'Journey total' : 'Total fuel cost'}</span><strong>{formatCurrency(result.totalCost, draft.fuelSettings.currency)}</strong></div></div>
      <p className={classes('live-result-note')}>This split updates automatically as you edit trip details.</p>
      {result.unassignedLegIds.length > 0 || result.unassignedExpenseIds.length > 0 ? <div className={classes('notice warning-notice')} role="status"><CircleAlert /><div><strong>{result.unassignedExpenseIds.length === 0 ? 'Some legs have no riders' : 'Some costs have no riders'}</strong><ul>{result.unassignedLegIds.map((id) => { const leg = draft.legs.find((item) => item.id === id)!; return <li key={id}>{result.unassignedExpenseIds.length > 0 && 'Leg: '}{stopsById.get(leg.fromStopId)} → {stopsById.get(leg.toStopId)}</li> })}{result.unassignedExpenseIds.map((id) => <li key={id}>Expense: {(draft.expenses ?? []).find((expense) => expense.id === id)?.name || 'Unnamed expense'}</li>)}</ul></div></div> : <div className={classes('split-list')}>{result.people.map((person) => <div className={classes('split-row')} key={person.personId}><div className={classes('avatar')} aria-hidden="true">{person.personName.charAt(0).toUpperCase()}</div><div><strong>{person.personName}</strong><span>{result.totalAdditionalCost > 0 ? `Fuel ${formatCurrency(person.fuelCost, draft.fuelSettings.currency)} + expenses ${formatCurrency(person.expenseCost, draft.fuelSettings.currency)}` : `${distanceFromKm(person.distanceKm, unitSystem).toLocaleString(undefined, { maximumFractionDigits: 2 })} ${units.distance} · ${person.legIds.length} ${person.legIds.length === 1 ? 'leg' : 'legs'}`}</span></div><strong>{formatCurrency(person.displayCost, draft.fuelSettings.currency)}</strong></div>)}</div>}
      <details className={classes('calculation-details')}><summary>How this was calculated <ChevronDown aria-hidden="true" /></summary><div className={classes('calculation-content')}><section><h3>Route totals and formula</h3><p>{result.totalDistanceKm.toLocaleString(undefined, { maximumFractionDigits: 2 })} km ÷ {draft.fuelSettings.fuelEconomyKmpl!.toLocaleString()} km/L = {result.totalLitres.toLocaleString(undefined, { maximumFractionDigits: 2 })} L</p><p>{result.totalLitres.toLocaleString(undefined, { maximumFractionDigits: 2 })} L × {formatCurrency(draft.fuelSettings.fuelPricePerLitre!, draft.fuelSettings.currency)} per litre = {formatCurrency(result.totalFuelCost, draft.fuelSettings.currency)}</p><p>Fuel {formatCurrency(result.totalFuelCost, draft.fuelSettings.currency)} + expenses {formatCurrency(result.totalAdditionalCost, draft.fuelSettings.currency)} = {formatCurrency(result.totalCost, draft.fuelSettings.currency)}</p></section><div className={classes('formula-box')}>Each rider’s total = fuel shares for their legs + fixed expenses assigned to them</div><section><h3>Per-leg allocation</h3><div className={classes('allocation-list')}>{calculationLegs.map(({ leg, riders, cost }) => <div className={classes('allocation-row')} key={leg.id}><strong>{stopsById.get(leg.fromStopId)} → {stopsById.get(leg.toStopId)}</strong><span>{leg.distanceKm!.toLocaleString()} km · {formatCurrency(cost, draft.fuelSettings.currency)} · {riders.length === 0 ? 'No riders assigned' : `${formatCurrency(cost / riders.length, draft.fuelSettings.currency)} each for ${riders.map(({ name }) => name).join(', ')}`}</span></div>)}</div></section><section><h3>Rounding</h3><p>Calculations keep full precision. Displayed shares use the currency’s minor units, then any leftover units go to the largest fractional remainders (ties follow rider order) so the displayed shares add up exactly to the rounded total.</p></section></div></details>
      <div className={classes('share-area')}><button className={classes('share-button')} type="button" disabled={shareStatus === 'sharing'} onClick={onShare}><Share2 size={18} />{shareStatus === 'sharing' ? 'Preparing summary…' : 'Share summary'}</button>{shareStatus === 'shared' && <p className={classes('share-status')} role="status">Summary shared.</p>}{shareStatus === 'downloaded' && <p className={classes('share-status')} role="status">Summary image downloaded.{shareMessageCopied ? ' Message copied to clipboard.' : ''}</p>}{shareStatus === 'error' && <p className={classes('share-status share-error')} role="alert">{shareError}</p>}</div>
    </>}
  </section>
}
